spring:
  application:
    name: fundingaccount
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/helpline?createDatabaseIfNotExist=true&amp;useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: Passw0rd
    continueOnError: true
    max-active: 20
    max-wait: 10
    max-idle: 10
    test-on-borrow: true
    validationQuery: SELECT 1
    jpa:
      hibernate:
        ddl-auto: create-drop
        globally_quoted_identifiers: true
        naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
        show-sql: true
security:
  user:
    password: test
    name: test
logging:
  level:
    org.springframework.security: DEBUG
management:
    security:
        enabled: false